/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Saskyra
 */
public class BangunRuang extends javax.swing.JFrame {

    /**
     * Creates new form BangunRuang
     */
    public BangunRuang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sisiKubus = new javax.swing.JTextField();
        luasPermukaanKubus = new javax.swing.JTextField();
        VolumeKubus = new javax.swing.JTextField();
        hitungKubus = new javax.swing.JButton();
        backKubus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panjangBalok = new javax.swing.JTextField();
        luasPermukaanBalok = new javax.swing.JTextField();
        VolumeBalok = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lebarBalok = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tinggiBalok = new javax.swing.JTextField();
        hitungBalok = new javax.swing.JButton();
        backBalok = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tinggipris = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        VolumePrismaSegitiga = new javax.swing.JTextField();
        luasPermukaanPrismaSegitiga = new javax.swing.JTextField();
        alasSegitiga = new javax.swing.JTextField();
        tinggiSegitiga = new javax.swing.JTextField();
        hitungPrismaSegitiga = new javax.swing.JButton();
        backPrisma = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        luasPermukaanBola = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jejariBola = new javax.swing.JTextField();
        volumeBola = new javax.swing.JTextField();
        hitungBola = new javax.swing.JButton();
        backBola = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(237, 221, 237));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setText("Bangun Ruang");

        jLabel6.setText("Sisi                      :");

        jLabel7.setText("Luas Permukaan  :");

        jLabel8.setText("Volume               :");

        sisiKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisiKubusActionPerformed(evt);
            }
        });

        luasPermukaanKubus.setEditable(false);
        luasPermukaanKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasPermukaanKubusActionPerformed(evt);
            }
        });

        VolumeKubus.setEditable(false);
        VolumeKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeKubusActionPerformed(evt);
            }
        });

        hitungKubus.setText("Hitung");
        hitungKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungKubusActionPerformed(evt);
            }
        });

        backKubus.setText("Back");
        backKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backKubusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hitungKubus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backKubus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(VolumeKubus)
                        .addComponent(luasPermukaanKubus)
                        .addComponent(sisiKubus)))
                .addGap(131, 131, 131))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sisiKubus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(luasPermukaanKubus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(VolumeKubus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hitungKubus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backKubus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kubus", jPanel3);

        jLabel9.setText("Panjang               :");

        jLabel10.setText("Luas Permukaan  :");

        jLabel11.setText("Volume               :");

        luasPermukaanBalok.setEditable(false);
        luasPermukaanBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasPermukaanBalokActionPerformed(evt);
            }
        });

        VolumeBalok.setEditable(false);
        VolumeBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeBalokActionPerformed(evt);
            }
        });

        jLabel12.setText("Lebar                   :");

        lebarBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebarBalokActionPerformed(evt);
            }
        });

        jLabel13.setText("Tinggi                  :");

        tinggiBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiBalokActionPerformed(evt);
            }
        });

        hitungBalok.setText("Hitung");
        hitungBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBalokActionPerformed(evt);
            }
        });

        backBalok.setText("Back");
        backBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBalokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tinggiBalok)
                            .addComponent(lebarBalok)
                            .addComponent(panjangBalok)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VolumeBalok)
                            .addComponent(luasPermukaanBalok)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(hitungBalok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(backBalok)
                                .addGap(0, 3, Short.MAX_VALUE)))))
                .addGap(129, 129, 129))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(panjangBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lebarBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tinggiBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(luasPermukaanBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(VolumeBalok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungBalok)
                    .addComponent(backBalok))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Balok", jPanel4);

        jLabel17.setText("Tinggi Prisma    :");

        jLabel18.setText("Tinggi Segitiga  :");

        jLabel19.setText("Alas Segitiga     :");

        jLabel20.setText("Luas Permukaan  :");

        jLabel21.setText("Volume             :");

        VolumePrismaSegitiga.setEditable(false);
        VolumePrismaSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumePrismaSegitigaActionPerformed(evt);
            }
        });

        luasPermukaanPrismaSegitiga.setEditable(false);
        luasPermukaanPrismaSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasPermukaanPrismaSegitigaActionPerformed(evt);
            }
        });

        alasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alasSegitigaActionPerformed(evt);
            }
        });

        tinggiSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiSegitigaActionPerformed(evt);
            }
        });

        hitungPrismaSegitiga.setText("Hitung");
        hitungPrismaSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungPrismaSegitigaActionPerformed(evt);
            }
        });

        backPrisma.setText("Back");
        backPrisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPrismaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(hitungPrismaSegitiga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backPrisma)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(VolumePrismaSegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(luasPermukaanPrismaSegitiga)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alasSegitiga)
                            .addComponent(tinggiSegitiga)
                            .addComponent(tinggipris))))
                .addGap(130, 130, 130))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tinggipris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tinggiSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(alasSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(luasPermukaanPrismaSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(VolumePrismaSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungPrismaSegitiga)
                    .addComponent(backPrisma))
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Prisma Segitiga", jPanel5);

        jLabel3.setText("Jari-jari            :");

        luasPermukaanBola.setEditable(false);
        luasPermukaanBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasPermukaanBolaActionPerformed(evt);
            }
        });

        jLabel4.setText("Luas Permukaan  :");

        jLabel5.setText("Volume           :");

        volumeBola.setEditable(false);
        volumeBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeBolaActionPerformed(evt);
            }
        });

        hitungBola.setText("Hitung");
        hitungBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBolaActionPerformed(evt);
            }
        });

        backBola.setText("Back");
        backBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hitungBola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backBola))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(volumeBola)
                            .addComponent(luasPermukaanBola)
                            .addComponent(jejariBola))
                        .addGap(2, 2, 2)))
                .addGap(134, 134, 134))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jejariBola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(luasPermukaanBola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(volumeBola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungBola)
                    .addComponent(backBola))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bola", jPanel2);

        jLabel2.setText("Pilih Bangun Ruang :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void luasPermukaanBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasPermukaanBolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasPermukaanBolaActionPerformed

    private void volumeBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeBolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeBolaActionPerformed

    private void luasPermukaanKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasPermukaanKubusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasPermukaanKubusActionPerformed

    private void VolumeKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeKubusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolumeKubusActionPerformed

    private void luasPermukaanBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasPermukaanBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasPermukaanBalokActionPerformed

    private void VolumeBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolumeBalokActionPerformed

    private void lebarBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebarBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lebarBalokActionPerformed

    private void tinggiBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiBalokActionPerformed

    private void VolumePrismaSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumePrismaSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolumePrismaSegitigaActionPerformed

    private void luasPermukaanPrismaSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasPermukaanPrismaSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasPermukaanPrismaSegitigaActionPerformed

    private void alasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alasSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alasSegitigaActionPerformed

    private void tinggiSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiSegitigaActionPerformed

    private void hitungBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBalokActionPerformed
        // TODO add your handling code here:
        double panjang = Double.parseDouble(panjangBalok.getText());
        double lebar = Double.parseDouble(lebarBalok.getText());
        double tinggi = Double.parseDouble(tinggiBalok.getText());
        
        double luasPermukaan = (2 * ((panjang * lebar) + (panjang * tinggi) + (lebar  * tinggi)));
        luasPermukaanBalok.setText(String.valueOf(luasPermukaan));
        
        double Volume = (panjang * lebar * tinggi);
        VolumeBalok.setText(String.valueOf(Volume));
        
    }//GEN-LAST:event_hitungBalokActionPerformed

    private void sisiKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisiKubusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisiKubusActionPerformed

    private void hitungBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBolaActionPerformed
        // TODO add your handling code here:
        double jejari = Double.parseDouble(jejariBola.getText());
        
        double luasPermukaan = (2 * (4/3 * Math.PI * (jejari * jejari * jejari)));
        luasPermukaanBola.setText(String.valueOf(luasPermukaan));
        
        double Volume = (4 * Math.PI * (jejari * jejari));
        volumeBola.setText(String.valueOf(Volume));
    }//GEN-LAST:event_hitungBolaActionPerformed

    private void hitungKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungKubusActionPerformed
        // TODO add your handling code here:
        double sisi = Double.parseDouble(sisiKubus.getText());
        
        double luasPermukaan = (sisi * sisi);
        luasPermukaanKubus.setText(String.valueOf(luasPermukaan));
        
        double Volume = (4 * sisi);
        VolumeKubus.setText(String.valueOf(Volume));
    }//GEN-LAST:event_hitungKubusActionPerformed

    private void hitungPrismaSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungPrismaSegitigaActionPerformed
        // TODO add your handling code here:
        double alas = Double.parseDouble(alasSegitiga.getText());
        double tinggip = Double.parseDouble(tinggipris.getText());
        double tinggi = Double.parseDouble(tinggiSegitiga.getText());
        
        double sisiMiringSegitiga  = (Math.sqrt(alas * alas) + (tinggi * tinggi));
        
        double luasPermukaan = ((2 * (0.5 * alas * tinggi)) + ((alas + tinggi + sisiMiringSegitiga) * tinggip));
        luasPermukaanPrismaSegitiga.setText(String.valueOf(luasPermukaan));
        
        double Volume = ((0.5 * alas * tinggi) * tinggip);
        VolumePrismaSegitiga.setText(String.valueOf(Volume));
    }//GEN-LAST:event_hitungPrismaSegitigaActionPerformed

    private void backBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBalokActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBalokActionPerformed

    private void backPrismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPrismaActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backPrismaActionPerformed

    private void backKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backKubusActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backKubusActionPerformed

    private void backBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBolaActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangunRuang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VolumeBalok;
    private javax.swing.JTextField VolumeKubus;
    private javax.swing.JTextField VolumePrismaSegitiga;
    private javax.swing.JTextField alasSegitiga;
    private javax.swing.JButton backBalok;
    private javax.swing.JButton backBola;
    private javax.swing.JButton backKubus;
    private javax.swing.JButton backPrisma;
    private javax.swing.JButton hitungBalok;
    private javax.swing.JButton hitungBola;
    private javax.swing.JButton hitungKubus;
    private javax.swing.JButton hitungPrismaSegitiga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jejariBola;
    private javax.swing.JTextField lebarBalok;
    private javax.swing.JTextField luasPermukaanBalok;
    private javax.swing.JTextField luasPermukaanBola;
    private javax.swing.JTextField luasPermukaanKubus;
    private javax.swing.JTextField luasPermukaanPrismaSegitiga;
    private javax.swing.JTextField panjangBalok;
    private javax.swing.JTextField sisiKubus;
    private javax.swing.JTextField tinggiBalok;
    private javax.swing.JTextField tinggiSegitiga;
    private javax.swing.JTextField tinggipris;
    private javax.swing.JTextField volumeBola;
    // End of variables declaration//GEN-END:variables
}
