/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Saskyra
 */
public class BangunDatar extends javax.swing.JFrame {

    /**
     * Creates new form BangunDatar
     */
    public BangunDatar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jariJariLingkaran2 = new javax.swing.JTextField();
        hitungLingkaran2 = new javax.swing.JButton();
        kelilingLingaran2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        luasLingkaran2 = new javax.swing.JTextField();
        backLingkaran = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        sisiPersegi = new javax.swing.JTextField();
        hitungPersegi = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        luasPersegi = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        kelilingPersegi = new javax.swing.JTextField();
        backPersegi = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        panjangPersegiPanjang = new javax.swing.JTextField();
        hitungPersegiPanjang = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        luasPersegiPanjang = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        kelilingPersegiPanjang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lebarPersegiPanjang = new javax.swing.JTextField();
        backPersegiPanjang = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        alasSegitiga = new javax.swing.JTextField();
        tinggiSegitiga = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        luasSegitiga = new javax.swing.JTextField();
        kelilingSegitiga = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        hitungSegitiga = new javax.swing.JButton();
        backSegitiga = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Jari-Jari :");

        jariJariLingkaran2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jariJariLingkaranActionPerformed(evt);
            }
        });

        hitungLingkaran2.setText("Hitung");
        hitungLingkaran2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungLingkaranActionPerformed(evt);
            }
        });

        kelilingLingaran2.setEditable(false);
        kelilingLingaran2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelilingLingaranActionPerformed(evt);
            }
        });

        jLabel14.setText("Keliling :");

        jLabel15.setText("Luas     :");

        luasLingkaran2.setEditable(false);

        backLingkaran.setText("Back");
        backLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLingkaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jariJariLingkaran2)
                        .addComponent(luasLingkaran2)
                        .addComponent(kelilingLingaran2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(hitungLingkaran2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backLingkaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jariJariLingkaran2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(luasLingkaran2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelilingLingaran2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungLingkaran2)
                    .addComponent(backLingkaran))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Lingkaran", jPanel4);

        jLabel16.setText("Sisi       : ");

        sisiPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisiPersegiActionPerformed(evt);
            }
        });

        hitungPersegi.setText("Hitung");
        hitungPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungPersegiActionPerformed(evt);
            }
        });

        jLabel17.setText("Luas     :");

        luasPersegi.setEditable(false);

        jLabel18.setText("Keliling :");

        kelilingPersegi.setEditable(false);
        kelilingPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelilingPersegiActionPerformed(evt);
            }
        });

        backPersegi.setText("Back");
        backPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPersegiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(hitungPersegi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backPersegi))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sisiPersegi)
                        .addComponent(luasPersegi)
                        .addComponent(kelilingPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(sisiPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(luasPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelilingPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hitungPersegi)
                    .addComponent(backPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Persegi", jPanel5);

        jLabel19.setText("Panjang   :");

        panjangPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjangPersegiPanjangActionPerformed(evt);
            }
        });

        hitungPersegiPanjang.setText("Hitung");
        hitungPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungPersegiPanjangActionPerformed(evt);
            }
        });

        jLabel20.setText("Luas        :");

        luasPersegiPanjang.setEditable(false);

        jLabel21.setText("Keliling    :");

        kelilingPersegiPanjang.setEditable(false);
        kelilingPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelilingPersegiPanjangActionPerformed(evt);
            }
        });

        jLabel2.setText("Lebar       :");

        lebarPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lebarPersegiPanjangActionPerformed(evt);
            }
        });

        backPersegiPanjang.setText("Back");
        backPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPersegiPanjangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21)
                        .addComponent(jLabel20))
                    .addComponent(jLabel19)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(hitungPersegiPanjang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backPersegiPanjang))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(kelilingPersegiPanjang, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lebarPersegiPanjang, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(luasPersegiPanjang, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panjangPersegiPanjang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panjangPersegiPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lebarPersegiPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luasPersegiPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelilingPersegiPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backPersegiPanjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hitungPersegiPanjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Persegi Panjang", jPanel6);

        jLabel22.setText("Alas       :");

        jLabel4.setText("Tinggi    :");

        alasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alasSegitigaActionPerformed(evt);
            }
        });

        tinggiSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiSegitigaActionPerformed(evt);
            }
        });

        jLabel23.setText("Luas       :");

        luasSegitiga.setEditable(false);

        kelilingSegitiga.setEditable(false);
        kelilingSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelilingSegitigaActionPerformed(evt);
            }
        });

        jLabel24.setText("Keliling   :");

        hitungSegitiga.setText("Hitung");
        hitungSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungSegitigaActionPerformed(evt);
            }
        });

        backSegitiga.setText("Back");
        backSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSegitigaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(alasSegitiga, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tinggiSegitiga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hitungSegitiga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backSegitiga))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(luasSegitiga)
                                .addComponent(kelilingSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alasSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tinggiSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luasSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelilingSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backSegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hitungSegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Segitiga", jPanel1);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setText("Bangun Datar");

        jLabel1.setText("Pilih Bangun Datar :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungSegitigaActionPerformed
        // TODO add your handling code here:
        double alas = Double.parseDouble(alasSegitiga.getText());
        double tinggi = Double.parseDouble(tinggiSegitiga.getText());

        double sisiMiring = (Math.sqrt(alas * alas) + (tinggi * tinggi));

        double luas = (0.5 * alas * tinggi);
        luasSegitiga.setText(String.valueOf(luas));

        double keliling = (alas + tinggi + sisiMiring);
        kelilingSegitiga.setText(String.valueOf(keliling));

    }//GEN-LAST:event_hitungSegitigaActionPerformed

    private void kelilingSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelilingSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelilingSegitigaActionPerformed

    private void tinggiSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiSegitigaActionPerformed

    private void alasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alasSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alasSegitigaActionPerformed

    private void lebarPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lebarPersegiPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lebarPersegiPanjangActionPerformed

    private void kelilingPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelilingPersegiPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelilingPersegiPanjangActionPerformed

    private void hitungPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungPersegiPanjangActionPerformed
        // TODO add your handling code here:
        double panjang = Double.parseDouble(panjangPersegiPanjang.getText());
        double lebar = Double.parseDouble(lebarPersegiPanjang.getText());

        double luas = (panjang * lebar);
        luasPersegiPanjang.setText(String.valueOf(luas));

        double keliling = (2 * (panjang + lebar));
        kelilingPersegiPanjang.setText(String.valueOf(keliling));
    }//GEN-LAST:event_hitungPersegiPanjangActionPerformed

    private void panjangPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjangPersegiPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panjangPersegiPanjangActionPerformed

    private void kelilingPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelilingPersegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelilingPersegiActionPerformed

    private void hitungPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungPersegiActionPerformed
        // TODO add your handling code here:
        double sisi = Double.parseDouble(sisiPersegi.getText());

        double luas = (sisi * sisi);
        luasPersegi.setText(String.valueOf(luas));

        double keliling = (4 * sisi);
        kelilingPersegi.setText(String.valueOf(keliling));
    }//GEN-LAST:event_hitungPersegiActionPerformed

    private void sisiPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisiPersegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sisiPersegiActionPerformed

    private void kelilingLingaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelilingLingaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelilingLingaranActionPerformed

    private void hitungLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungLingkaranActionPerformed
        // TODO add your handling code here:
        double jariJari = Double.parseDouble(jariJariLingkaran.getText());

        double luas = (Math.PI * jariJari * jariJari);
        luasLingkaran.setText(String.valueOf(luas));

        double keliling = (2 * Math.PI * jariJari);
        kelilingLingaran.setText(String.valueOf(keliling));
    }//GEN-LAST:event_hitungLingkaranActionPerformed

    private void jariJariLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jariJariLingkaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jariJariLingkaranActionPerformed

    private void backLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLingkaranActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backLingkaranActionPerformed

    private void backPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPersegiActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backPersegiActionPerformed

    private void backPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPersegiPanjangActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backPersegiPanjangActionPerformed

    private void backSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSegitigaActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backSegitigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangunDatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangunDatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alasSegitiga;
    private javax.swing.JButton backLingkaran;
    private javax.swing.JButton backPersegi;
    private javax.swing.JButton backPersegiPanjang;
    private javax.swing.JButton backSegitiga;
    private javax.swing.JButton hitungLingkaran;
    private javax.swing.JButton hitungLingkaran1;
    private javax.swing.JButton hitungLingkaran2;
    private javax.swing.JButton hitungPersegi;
    private javax.swing.JButton hitungPersegiPanjang;
    private javax.swing.JButton hitungSegitiga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jariJariLingkaran;
    private javax.swing.JTextField jariJariLingkaran1;
    private javax.swing.JTextField jariJariLingkaran2;
    private javax.swing.JTextField kelilingLingaran;
    private javax.swing.JTextField kelilingLingaran1;
    private javax.swing.JTextField kelilingLingaran2;
    private javax.swing.JTextField kelilingPersegi;
    private javax.swing.JTextField kelilingPersegiPanjang;
    private javax.swing.JTextField kelilingSegitiga;
    private javax.swing.JTextField lebarPersegiPanjang;
    private javax.swing.JTextField luasLingkaran;
    private javax.swing.JTextField luasLingkaran1;
    private javax.swing.JTextField luasLingkaran2;
    private javax.swing.JTextField luasPersegi;
    private javax.swing.JTextField luasPersegiPanjang;
    private javax.swing.JTextField luasSegitiga;
    private javax.swing.JTextField panjangPersegiPanjang;
    private javax.swing.JTextField sisiPersegi;
    private javax.swing.JTextField tinggiSegitiga;
    // End of variables declaration//GEN-END:variables
}
